#include <iostream>
#include <iostream>
#include "matrix_operations.h"
#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include <unistd.h>
#include <sys/types.h>
//#include <sys/wait.h>
#include <fstream>
#include <fcntl.h>
#include <cstring>
#include <fstream>
#include <string>
#include <bits/stdc++.h>
#include <map>
#include <array>

#include "matrix_operations.h"

using namespace std;

int main() {




    /* Create matricies Mat_A & Mat_B (decimals) with dimensions N x N, where N is an arbitrarily large number.
    * (the wrapup report will likely need evidence of experimenting with multiple N instances) <-- perhaps code could be written where the matricies are re-generated multiple times
    * could attempt to utilize dynamic arrays (possible extra credit?)
    * matrix addition code is in Canvas
    */

    /* following code was initially generated by ChatGPT, using the prompt "write a c++ program that matrix multiplies a pair of dynamic arrays into a third"
     * functionality has been added by me to include the following:
     * [ ] Prompt the user for the size of the dynamic arrays
     * [ ] fill each array with randomly generated numbers
     */

    matrix_operations m;
    int dim;
    int r1, c1, r2, c2;
    int userInput;

    // get user input into num of rows & columns. weak working solution for now, as input validation not great
    cout << "How many rows & columns would you like for Matrix A: ";
    cin >> userInput;
    if (cin.fail()) {
        cout << "wasn't an int, exiting process";
        return 0;
    }

    // Creates arrays for A, B & C
    int** A = new int*[dim];
    int** B = new int*[dim];
    int** C = new int*[dim];

    for (int i = 0; i < dim; i++) {
        A[i] = new int[dim];
        C[i] = new int[dim];
        B[i] = new int[dim];
    }

    // fill matrix A & B with random integer numbers
    m.inputMatrix(A, dim);
    m.inputMatrix(B, dim);

    // Initialize result matrix C to 0
    // this was generated, not sure if necessary
    for (int i = 0; i < dim; i++) {
        for (int j = 0; j < dim; j++) {
            C[i][j] = 0;
        }
    }

    // Matrix multiplication
    for (int i = 0; i < r1; i++) {
        for (int j = 0; j < c2; j++) {
            for (int k = 0; k < c1; k++) {
                C[i][j] += A[i][k] * B[k][j];
            }
        }
    }

    // Output result
    cout << "Resultant Matrix C:\n";
    for (int i = 0; i < r1; i++) {
        for (int j = 0; j < c2; j++) {
            cout << C[i][j] << " ";
        }
        cout << endl;
    }

    // Free allocated memory
    for (int i = 0; i < r1; i++) {
        delete[] A[i];
        delete[] C[i];
    }
    for (int i = 0; i < r2; i++) {
        delete[] B[i];
    }

    delete[] A;
    delete[] B;
    delete[] C;



    /* Matrix multiply Mat_A & Mat_B into a same size matrix Mat_C (also decimals)
     * This process is supposed to be using multithreading.
     *
     */

    /* results could be exported into an excel file if possible?? would be considered extra credit if the solution generated and formatted itself.
     *
     */

    return 0;
}