#include <iostream>
#include <iostream>
#include "matrix_operations.h"
#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include <unistd.h>
#include <sys/types.h>
//#include <sys/wait.h>
#include <fstream>
#include <fcntl.h>
#include <cstring>
#include <fstream>
#include <string>
#include <bits/stdc++.h>
#include <map>
#include <array>
#include <vector>
#include <chrono>

#include "matrix_operations.h"

using namespace std;
using namespace std::chrono; // for the   high_resolution_clock


int dim = 0;
vector<vector<unsigned long long int>> matrixA;
vector<vector<unsigned long long int>> matrixB;
vector<vector<unsigned long long int>> matrixC; // Sequential
vector<vector<unsigned long long int>> matrixD; // Parallel Multithread

// Constructs the vector matrices
// Code from matrix addition example
void constructMatricies(int dim) {
    for (int i = 0; i < dim; i++) {
        matrixA.push_back(vector<unsigned long long int>(dim));
        matrixB.push_back(vector<unsigned long long int>(dim));
        matrixC.push_back(vector<unsigned long long int>(dim));
        matrixD.push_back(vector<unsigned long long int>(dim));
    }
}

/* sequentially carries out matrix multiplication
 * Modification of matrix C to accomplish this
 */
void sequential_Matrix_Multiplication() {
    for (int i = 0; i < dim; i++) {
        for (int j = 0; j < dim; j++) {
            for (int k = 0; k < dim; k++) {
                matrixC[i][j] += matrixA[i][k] * matrixB[k][j];
            }
        }
    }
}



/* matrix multiplies based on the chunk given via "start" and "end" variables in first column
 * to be run in parallel to other threads containing this function
 * modification of matrix D to accomplish this,
*/
void parallel_Matrix_Multiplication(int start, int end) {
    for (int i = start; i < end; i++) {
        for (int j = 0; j < dim; j++) {
            for (int k = 0; k < dim; k++) {
                matrixD[i][j] += matrixA[i][k] * matrixB[k][j];
            }
        }
    }
}

int main() {

    /* Create matricies Mat_A & Mat_B (decimals) with dimensions N x N, where N is an arbitrarily large number.
    * (the wrapup report will likely need evidence of experimenting with multiple N instances) <-- perhaps code could be written where the matricies are re-generated multiple times
    * could attempt to utilize dynamic arrays (possible extra credit?)
    * matrix addition code is in Canvas
    */

    /* following code was initially generated by ChatGPT, using the prompt "write a c++ program that matrix multiplies a pair of dynamic arrays into a third"
     * functionality has been added by me to include the following:
     * [ ] Prompt the user for the size of the dynamic arrays
     * [ ] fill each array with randomly generated numbers
     */

    matrix_operations m;

    int userInput;

    // get user input into num of rows & columns. weak working solution for now, as input validation not great
    cout << "How many rows & columns would you like for each Matrix?: ";
    cin >> userInput;
    if (cin.fail()) {
        cout << "wasn't an int, exiting process";
        return 0;
    }
    dim = userInput;
    constructMatricies(dim);


    // fills vectors with junk values
    for (int i = 0; i < dim; i++) {
        for (int j = 0; j < dim; j++) {
            matrixA[i][j] = rand() % 11;
            matrixB[i][j] = rand() % 11;
        }
    }
    for (int i = 0; i < dim; i++) {
        for (int j = 0; j < dim; j++) {
            if (matrixA[i][j] > 10 || matrixA[i][j] < 0) return 1;
            if (matrixB[i][j] > 10 || matrixB[i][j] < 0) return 1;
        }
    }



    srand((unsigned) time(0));
    // fill matrix A & B with random integer numbers
    // m.inputMatrix(A, dim);
    // m.inputMatrix(B, dim);

    // Initialize result matrix C to 0
    for (int i = 0; i < dim; i++) {
        for (int j = 0; j < dim; j++) {
            matrixC[i][j] = 0;
            matrixD[i][j] = 0;
        }
    }

    /* Matrix multiplication. This is what is to be multithreadded in one of two ways
     * Attempting to split the matrix into quadrants & running at the same time in that way.
     */
    // currently sequential only

    cout << "Start Sequential Operation " << endl;
    auto start = high_resolution_clock::now();

    sequential_Matrix_Multiplication();

    auto stop = high_resolution_clock::now();
    auto duration = duration_cast<microseconds>(stop - start);
    cout << "Sequential time: " << duration.count() << endl;


    // $$$$$$$$$$$$$$$$$$$$$$$$$$$$ END OF SEQUENTIAL $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

    // Multithreading

    int numThreads = 4;
    cout << "Start Parallel Operation Using std::theard" << endl;
    start = high_resolution_clock::now();
    //creating threads and dividing the workload

    /* Splitting the size into 4 parts
     *
     */

    int workload = dim / 4;
    int dim1 = workload;
    int dim2 = workload * 2;
    int dim3 = workload * 3;
    int dim4 = dim - 1;

    thread th1(parallel_Matrix_Multiplication, 0, dim1);
    thread th2(parallel_Matrix_Multiplication, (dim1 + 1), dim2);
    thread th3(parallel_Matrix_Multiplication, (dim2 + 1), dim3);
    thread th4(parallel_Matrix_Multiplication, (dim3 + 1), dim4);

    th1.join();
    th2.join();
    th3.join();
    th4.join();

    stop = high_resolution_clock::now();
    duration = duration_cast<microseconds>(stop - start);
    cout << "Parallel time in microseconds: " << duration.count() << endl;


    // $$$$$$$$$$$$$$$$$$$$$$$$$$$$ END OF MULTITHREADING $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

    // cout << "output matrix A" << endl;
    // m.outputMatrix(matrixA, dim);
    // cout << "output matrix B" << endl;
    // m.outputMatrix(matrixB, dim);
    // cout << "output matrix C" << endl;
    // m.outputMatrix(matrixC, dim);

    // Free allocated memory
    // for (int i = 0; i < dim; i++) {
    //     delete[] A[i];
    //     delete[] C[i];
    // }
    // for (int i = 0; i < dim; i++) {
    //     delete[] B[i];
    // }
    //
    // delete[] A;
    // delete[] B;
    // delete[] C;



    /* Matrix multiply Mat_A & Mat_B into a same size matrix Mat_C (also decimals)
     * This process is supposed to be using multithreading.
     *
     */


    return 0;
}