#include <iostream>
#include "matrix_operations.h"
#include "dynamic_arrays.h"

int main() {

    DynamicArray d;


    /* Create matricies Mat_A & Mat_B (decimals) with dimensions N x N, where N is an arbitrarily large number.
    * (the wrapup report will likely need evidence of experimenting with multiple N instances) <-- perhaps code could be written where the matricies are re-generated multiple times
    * could attempt to utilize dynamic arrays (possible extra credit?)
    * matrix addition code is in Canvas
    */

    /* following code was initially generated by ChatGPT, using the prompt "write a c++ program that matrix multiplies a pair of dynamic arrays into a third"
     * functionality has been added by me to include the following:
     * [ ] Prompt the user for the size of the dynamic arrays
     * [ ] fill each array with randomly generated numbers
     */

    int r1, c1, r2, c2;

    // Input matrix dimensions
    cout << "Enter rows and columns for Matrix A: ";
    cin >> r1 >> c1;

    cout << "Enter rows and columns for Matrix B: ";
    cin >> r2 >> c2;

    // Check if multiplication is possible
    if (c1 != r2) {
        cout << "Matrix multiplication not possible!" << endl;
        return 1;
    }

    // Dynamically allocate matrices
    int** A = new int*[r1];
    int** B = new int*[r2];
    int** C = new int*[r1];

    for (int i = 0; i < r1; i++) {
        A[i] = new int[c1];
        C[i] = new int[c2];
    }

    for (int i = 0; i < r2; i++) {
        B[i] = new int[c2];
    }


    // Input Matrix A
    cout << "Enter elements of Matrix A:\n";
    for (int i = 0; i < r1; i++) {
        for (int j = 0; j < c1; j++) {
            cin >> A[i][j];
        }
    }

    // Input Matrix B
    cout << "Enter elements of Matrix B:\n";
    for (int i = 0; i < r2; i++) {
        for (int j = 0; j < c2; j++) {
            cin >> B[i][j];
        }
    }

    // Initialize result matrix C to 0
    for (int i = 0; i < r1; i++) {
        for (int j = 0; j < c2; j++) {
            C[i][j] = 0;
        }
    }

    // Matrix multiplication
    for (int i = 0; i < r1; i++) {
        for (int j = 0; j < c2; j++) {
            for (int k = 0; k < c1; k++) {
                C[i][j] += A[i][k] * B[k][j];
            }
        }
    }

    // Output result
    cout << "Resultant Matrix C:\n";
    for (int i = 0; i < r1; i++) {
        for (int j = 0; j < c2; j++) {
            cout << C[i][j] << " ";
        }
        cout << endl;
    }

    // Free allocated memory
    for (int i = 0; i < r1; i++) {
        delete[] A[i];
        delete[] C[i];
    }
    for (int i = 0; i < r2; i++) {
        delete[] B[i];
    }

    delete[] A;
    delete[] B;
    delete[] C;



    /* Matrix multiply Mat_A & Mat_B into a same size matrix Mat_C (also decimals)
     * This process is supposed to be using multithreading.
     *
     */

    /* results could be exported into an excel file if possible?? would be considered extra credit if the solution generated and formatted itself.
     *
     */

    return 0;
}